name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: registry.liwanetworks.com
  IMAGE_NAME: mohamed/nextjs-demo
  IMAGE_TAG: 1.0.${{ github.run_number }}
  
jobs:

  build:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG}}
    
    - name: Log into registry ${{ env.REGISTRY }}
      run: docker login ${{ env.REGISTRY }} --username=${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
      
  deployment:
  
    runs-on: ubuntu-latest
    environment: deployment
    needs: build
    
    steps:
    - name: Push the Docker image
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG}}
    
